steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build the container image
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}-${_ENVIRONMENT}:$COMMIT_SHA",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: Push the container image to Container Registry
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}-${_ENVIRONMENT}:$COMMIT_SHA",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    id: Write environment variables
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo 'LOCATION_NAME: "${_REGION}"' >> ./infra/config/${_ENVIRONMENT}.yaml
        echo 'SERVICE_URI: "${_SERVICE_URI}"' >> ./infra/config/${_ENVIRONMENT}.yaml

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: Deploy container image to Cloud Run
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}${_SUFFIX}"
      - "--image"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}-${_ENVIRONMENT}:$COMMIT_SHA"
      - "--region"
      - "${_REGION}"
      - "--service-account"
      - "${_SERVICE_NAME}@$PROJECT_ID.iam.gserviceaccount.com"
      - "--allow-unauthenticated"
      - "--vpc-connector"
      - "projects/${_VPC_PROJECT_ID}/locations/${_REGION}/connectors/${_VPC_NAME}"
      - "--vpc-egress"
      - "private-ranges-only"
      - "--min-instances"
      - "${_MIN_INSTANCES}"
      - "--max-instances"
      - "${_MAX_INSTANCES}"
      - "--env-vars-file"
      - "./infra/config/${_ENVIRONMENT}.yaml"
      - "--set-secrets"
      - "DB_URI=${_ENVIRONMENT}_${_SERVICE_NAME}_DB_URI:latest"

logsBucket: "gs://${_SERVICE_NAME}-${_ENVIRONMENT}/cloud-build-logs"
options:
  logging: GCS_ONLY

substitutions:
  _SUFFIX: "-dev"
  _VPC_NAME: "conector-monitoring-dev"
  _VPC_PROJECT_ID: "monitoring-dev-2023"
  _ENVIRONMENT: dev
  _SERVICE_URI: ""
  _SERVICE_NAME: "monitoring-resource"
  _REGION: "us-central1"
  _MIN_INSTANCES: "0"
  _MAX_INSTANCES: "5"

images:
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}-${_ENVIRONMENT}:$COMMIT_SHA"
